# Generated by Django 3.0.3 on 2020-02-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonecas',
            name='status',
            field=models.CharField(choices=[('DISPONÍVEL', 'O item está disponível para compra'), ('ESGOTADO', 'Todos os itens foram vendidos'), ('RESTOCKING', 'Novos itens com a especificação chegarão em breve')], default='RESTOCKING', max_length=200),
        ),
        migrations.AlterField(
            model_name='bonecos',
            name='status',
            field=models.CharField(choices=[('DISPONÍVEL', 'O item está disponível para compra'), ('ESGOTADO', 'Todos os itens foram vendidos'), ('RESTOCKING', 'Novos itens com a especificação chegarão em breve')], default='RESTOCKING', max_length=200),
        ),
        migrations.AlterField(
            model_name='brindes',
            name='status',
            field=models.CharField(choices=[('DISPONÍVEL', 'O item está disponível para compra'), ('ESGOTADO', 'Todos os itens foram vendidos'), ('RESTOCKING', 'Novos itens com a especificação chegarão em breve')], default='RESTOCKING', max_length=200),
        ),
        migrations.AlterField(
            model_name='carros',
            name='status',
            field=models.CharField(choices=[('DISPONÍVEL', 'O item está disponível para compra'), ('ESGOTADO', 'Todos os itens foram vendidos'), ('RESTOCKING', 'Novos itens com a especificação chegarão em breve')], default='RESTOCKING', max_length=200),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='status',
            field=models.CharField(choices=[('DISPONÍVEL', 'O item está disponível para compra'), ('ESGOTADO', 'Todos os itens foram vendidos'), ('RESTOCKING', 'Novos itens com a especificação chegarão em breve')], default='RESTOCKING', max_length=200),
        ),
        migrations.AlterField(
            model_name='outros',
            name='status',
            field=models.CharField(choices=[('DISPONÍVEL', 'O item está disponível para compra'), ('ESGOTADO', 'Todos os itens foram vendidos'), ('RESTOCKING', 'Novos itens com a especificação chegarão em breve')], default='RESTOCKING', max_length=200),
        ),
    ]
